### ISSUE TITLE
dfw in iptables mode can't find iptables-restore

### ISSUE THREAD

**Issue by cybermcm** [pitkley/dfw#269]
Trying out new dfw version but I'm stuck at the beginning. Using a blank .toml file.
Tried 1.2.0-rc.3, 1.2.0-rc.2 and 1.2.0-rc.1, none working
compose config:
```
dfw:
  cap_add:
   - NET_ADMIN
  command: --firewall-backend iptables --config-file /config/dfw.toml --log-level debug
  #command: --config-file /config/dfw.toml --log-level debug
  container_name: dfw
  image: pitkley/dfw
  network_mode: "host"
  restart: always
  volumes:
   - ${timezone}
   - ${localtime}
   - /var/run/docker.sock:/var/run/docker.sock
   - /opt/dfw/dfw.toml:/config/dfw.toml
```
log output:
```
dfw                     | May 31 09:19:16.173 INFO Starting processing, started_processing_at: 2020-05-31T7:19:16+0000, module: dfw::iptables::process:20
dfw                     | May 31 09:19:16.173 DEBG Starting sub-processing, part: global_defaults, module: dfw::iptables::process:193
dfw                     | May 31 09:19:16.173 INFO Finished processing, finished_processing_at: 2020-05-31T7:19:16+0000, module: dfw::iptables::process:130
dfw                     | May 31 09:19:16.173 INFO Applying IPv4 rules (using iptables-restore), module: dfw::iptables:50
dfw                     | May 31 09:19:16.175 ERRO Encountered error, backtrace: , error: No such file or directory (os error 2), module: dfw:561
```
Problem on my side? iptables-restore is available on my host (Debian 10.4) and working
