### ISSUE TITLE
Updated rules don't affect to current connection

### ISSUE THREAD

**Issue by lapnd** [pitkley/dfw#456]
Let say, we have a rule to allow container1 access internet
```toml
[container_to_wider_world]
default_policy = "reject"
[[container_to_wider_world.rules]]
network = "internal"
verdict = "accept"
src_container = "container1"
```
Inside the container1, there is a ssh connection to a public server.

However, after update the rule to reject internet access
```toml
[container_to_wider_world]
default_policy = "reject"
[[container_to_wider_world.rules]]
network = "internal"
verdict = "reject"
src_container = "container1"
```
The ssh connection is still a lived. It's expected that the connection should be dropped.
I tried to remove and start the dfw container again, but the connection is still not dropped
```sh
docker rm -f dfw
docker run -it \
    --name=dfw \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    -v $PWD/dfw.toml:/config/dfw.toml \
    --net host --cap-add=NET_ADMIN \
    pitkley/dfw:latest \
        --config-file /config/dfw.toml
```
